version : "3"
services : 
  foursquare-connector :
    build : ./build/FoursquareConnector/
    image : worker-01:5000/foursquare-connector
    extra_hosts :
      - "mongo:172.16.0.6"
    restart: always
    ports : 
      - 6006:6006
  twitter-connector :
    build : ./build/TwitterConnector/
    image : worker-01:5000/twitter-connector
    extra_hosts :
      - "mongo:172.16.0.6"
    restart: always
    ports :
      - 7777:7777
    depends_on :
      - socialdata-service
  facebook-connector :
    build : ./build/FacebookConnector/
    image : worker-01:5000/facebook-connector
    network_mode : "host"
    restart: always
    ports :
      - 6001:6001
  socialdata-service :
    build : ./build/SocialDataService/
    image : worker-01:5000/socialdata-service
    extra_hosts :
      - "mongo:172.16.0.6"
    restart: always
    ports : 
     - 5005:5005
  crowdflow-prediction :
    build : ./build/CrowdflowPrediction/
    image : worker-01:5000/crowdflow-prediction
    extra_hosts :
      - "mongo:172.16.0.6"
    restart: always
    ports :
      - 5050:5050
  sentimental-prediction :
    build : ./build/SentimentalPrediction/
    image : worker-01:5000/sentimental-prediction
    extra_hosts :
      - "mongo:172.16.0.6"
    restart: always
    ports :
      - 5006:5006
