version : "3"
services : 
  foursquare-connector :
    build : ./build/FoursquareConnector/
    image : worker-01:5000/cityservice-foursquare-connector
    #networks: 
    #  - default
    extra_hosts :
      - "mongo:172.16.0.6"
    restart: always
    ports : 
      - 6006:6006
  twitter-connector :
    build : ./build/TwitterConnector/
    image : worker-01:5000/cityservice-twitter-connector
    #networks: 
    #  - default
    extra_hosts :
      - "mongo:172.16.0.6"
    restart: always
    ports :
      - 7777:7777
    depends_on :
      - socialdata-service
  facebook-connector :
    build : ./build/FacebookConnector/
    image : worker-01:5000/cityservice-facebook-connector
    #networks: 
    #  - default
    restart: always
    ports :
      - 6001:6001
  socialdata-service :
    build : ./build/SocialDataService/
    image : worker-01:5000/cityservice-socialdata-service
    #networks: 
    #  - default
    extra_hosts :
      - "mongo:172.16.0.6"
    restart: always
    ports : 
     - 5005:5005
  crowdflow-prediction :
    build : ./build/CrowdflowPrediction/
    image : worker-01:5000/cityservice-crowdflow-prediction
    #networks: 
    #  - default
    extra_hosts :
      - "mongo:172.16.0.6"
    restart: always
    ports :
      - 5050:5050
  sentimental-prediction :
    build : ./build/SentimentalPrediction/
    image : worker-01:5000/cityservice-sentimental-prediction
    #networks: 
    #  - default
    extra_hosts :
      - "mongo:172.16.0.6"
    restart: always
    ports :
      - 5006:5006

#networks:
#  default:
#    driver: store/weaveworks/net-plugin:latest_release
